### ISSUE TITLE
Top Rated Show List

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#10]
1)  Switch show filter from right to left (same as song list)
2)  Rename "Reviews" to "Total Ratings", possibly have "reviews" as well?
3) Reduce dead spacing to maximize total # seen at a time
![image](https://cloud.githubusercontent.com/assets/27736500/25293060/01390302-26a7-11e7-9ca3-44d1a7d0d0ae.png)

**Comment by akosborn** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20467592/25316919/cdf0f8a8-2834-11e7-89c8-a0c2d987059a.PNG)
