### ISSUE TITLE
Menu Bar Ideal

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#3]
Menu Bar/Drop-Downs

[Menu Bar Ideal.pdf](https://github.com/akosborn/umspreadsheet_server/files/930550/Menu.Bar.Ideal.pdf)

**completed**

**Comment by EEslacker** [comment]
# About
## Rating System (Gaphic)
Diamond   9.00-10.00
Gold          8.00-9.00
Silver         7.00-8.00
Bronze      6.00-7.00 
## **Fan Created | Fan Driven**
- The goal of this website is to provide a unique and in-depth view of Umphrey's Mcgee's powerful and ongoing musical career.  
- This community based resource should help to promote dialogue between a variety of fans, old and new.
- This resource is **just for fun** and in no way should be viewed as belittling to any individual experience.  
## Disclaimer
- This is a non-profit driven website, created and maintained by fans and is not associated with Umphrey's Mcgee in any other way.
- Please do not infringe on any of Umphrey's McGee's Copyright Laws by sharing or posting links to copyrighted material.

**Comment by EEslacker** [comment]
Can we have Profile Bios?
- location
- favorite songs
- Avatar
- etc

**Comment by EEslacker** [comment]
When on "Show Filter" or "Song Filter", have the filter selection pane on the left side

**Comment by akosborn** [comment]
About page will be up tomorrow for sure.

As for profile bios, definitely. Want to see if I can incorporate messaging too at some point.

**Comment by EEslacker** [comment]
Here are some fixed logos Jeff made, the "sheet" in the other ones was
mis-aligned.  I'd like to use the new logo where applicable.


[image: Inline image 2][image: Inline image 1]

**Comment by akosborn** [comment]
Logos updated in body, navbar, and tab
![fixed](https://cloud.githubusercontent.com/assets/20467592/25307443/9912f772-2766-11e7-9a38-3f942a665104.PNG)

**Comment by akosborn** [comment]
Rating info font is all that's left. I threw in a shout-out to nugs.net, but let me know what you think.
![fixed](https://cloud.githubusercontent.com/assets/20467592/25310153/98961706-27a3-11e7-94da-e60dbfe9077b.PNG)
