### ISSUE TITLE
Show Font Spacing

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#4]
![image](https://cloud.githubusercontent.com/assets/27736500/25196593/259fb130-250f-11e7-9c10-16e09566ceb6.png)

**Comment by akosborn** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20467592/25292360/67666c48-269b-11e7-8b5f-7439297a60cc.PNG)

Is the uppermost symbol referring to the show title font size needing to be decreased or the spacing above it?
