### ISSUE TITLE
Change "Sets" font color different

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#6]
![image](https://cloud.githubusercontent.com/assets/27736500/25244763/0adb1a76-25d0-11e7-8674-c12c0fa28164.png)

**Comment by akosborn** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20467592/25257301/c0a3806a-25fc-11e7-8013-ff7c48eab50b.PNG)
