### ISSUE TITLE
Visual Rating Bar

### ISSUE THREAD

**Issue by akosborn** [akosborn/umspreadsheet_server#7]
Thoughts on this? 
![fixed](https://cloud.githubusercontent.com/assets/20467592/25263351/c50b7e82-2624-11e7-8669-9cdecf5956f7.PNG)

Going for something similar to this:
![fixed](https://cloud.githubusercontent.com/assets/20467592/25263372/f79bf6a6-2624-11e7-83ec-a7d443f6ce9d.PNG)

**Comment by EEslacker** [comment]
Excellent Idea, a few notes:
1) Can you make the lines a bit thicker to be more of a bar rather than a line?
2) Can you display the rating and the bar closer together, or possibly combined? seems odd they are so far away

**Comment by akosborn** [comment]
I actually really like this, but the logged-in view for the table simply doesn't have enough room to incorporate it. This is the view when not logged in. I'll likely leave it since there's plenty of room.
![fixed](https://cloud.githubusercontent.com/assets/20467592/25323585/dfe0dbea-2885-11e7-8590-884d2716422c.PNG)
