### ISSUE TITLE
Make "Sets/Encore" rows a different background color

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#8]
![image](https://cloud.githubusercontent.com/assets/27736500/25292721/5f403012-26a5-11e7-89d1-93df30b59cd2.png)

**Comment by akosborn** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20467592/25310562/9098b0b4-27ac-11e7-8e19-d457a3c99d02.PNG)
