### ISSUE TITLE
Top-Rated Songs List

### ISSUE THREAD

**Issue by EEslacker** [akosborn/umspreadsheet_server#9]
1) Can we switch the filter function to left side? I think it is more user intuitive (despite phish.net :))
2) Can we minimize all that dead space in-between songs?
3) can we display the comment icon to view those song's comments?
4) Possible to display total number of ratings per song? (useful on every page)
![image](https://cloud.githubusercontent.com/assets/27736500/25292960/843ccda2-26a6-11e7-8c30-2f2b31283187.png)

**Comment by akosborn** [comment]
Everything but comment link is done
![fixed](https://cloud.githubusercontent.com/assets/20467592/25310737/1b116452-27b2-11e7-8386-e0a013590ba0.PNG)

**Comment by akosborn** [comment]
Instead of adding a dedicated link to the comments, I made the song titles link to their respective pages where the comments can be seen.
![comments](https://cloud.githubusercontent.com/assets/20467592/26220369/f761bb9e-3bd7-11e7-8094-0c1fa0062bb9.PNG)
